version: "3.6"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "588324452158.dkr.ecr.eu-west-2.amazonaws.com/replaylist:Latest"
    container_name: replaylist-container
    ports:
      - "3000:3000"
    environment:
      - DEBUG=1
      - ENV_FILE_PATH=${ENV_FILE_PATH:-./packages/server/.env}
    env_file:
      - ${ENV_FILE_PATH}
